modLoader="javafml"
loaderVersion="[4,)"
license="${mod_license}"
issueTrackerURL="${issues_url}"


[[mods]]
    modId="${mod_id}"
    version="${mod_version}"
    displayName="${mod_name}"
    displayURL="${mod_url}"
    iconFile="assets/glowtone/icon.png"
    authors="Lufurrius, Luna/AViewFromTheTop"
    description='''
Allows for emissive textures to be quickly added as an overlay on both Block and Item models, as well as changing the render layers of blocks.
    '''

[[mixins]]
    config="glowtone.mixins.json"

[[mixins]]
    config="glowtone.neoforge.mixins.json"

[modproperties.glowtone]
    "sodium:config_api_user"="net.frozenblock.glowtone.config.sodium.GlowtoneSodiumConfig"

[[ dependencies.glowtone ]]
    modId="neoforge"
    type="required"
    versionRange="[${neoforge_version},)"
    ordering="NONE"
    side="BOTH"

[[ dependencies.glowtone ]]
    modId="minecraft"
    type="required"
    versionRange="[${minecraft_version},)"
    ordering="NONE"
    side="BOTH"

[[ dependencies.freezeframe ]]
    modId="frozenlib"
    type="required"
    versionRange="[${frozenlib_version},)"
    ordering="NONE"
    side="BOTH"
